#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env.hostinger"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"
STATE_DIR="$ROOT_DIR/.deploy_state"
RESTORE_FLAG="$STATE_DIR/db_restored.flag"
mkdir -p "$STATE_DIR"

for cmd in docker curl openssl; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "ERROR: falta comando '$cmd'"; exit 1; }
done

PUBLIC_IP="${PUBLIC_IP:-}"
[ -z "$PUBLIC_IP" ] && PUBLIC_IP="$(curl -4 -fsS ifconfig.me 2>/dev/null || true)"
PUBLIC_IP="${PUBLIC_IP:-127.0.0.1}"

POSTGRES_USER="${POSTGRES_USER:-sgs_user}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -base64 36 | tr -dc 'A-Za-z0-9' | head -c 32)}"
POSTGRES_DB="${POSTGRES_DB:-sgs_prod}"
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-sgs_minio}"
MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-$(openssl rand -base64 36 | tr -dc 'A-Za-z0-9' | head -c 32)}"
MINIO_BUCKET="${MINIO_BUCKET:-sgs-documentos}"
MINIO_PORT="${MINIO_PORT:-9100}"
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-9101}"
MINIO_PUBLIC_URL="${MINIO_PUBLIC_URL:-http://${PUBLIC_IP}:${MINIO_PORT}}"
OLLAMA_URL="${OLLAMA_URL:-http://TU_HOST_OLLAMA:11434}"
OLLAMA_MODEL="${OLLAMA_MODEL:-llama3.2:3b}"
IA_RESEARCH_PROVIDER="${IA_RESEARCH_PROVIDER:-openai}"
IA_RESEARCH_MODEL="${IA_RESEARCH_MODEL:-gpt-4.1-mini}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
GEMINI_API_KEY="${GEMINI_API_KEY:-}"
SECRET_KEY="${SECRET_KEY:-$(openssl rand -hex 64)}"
ACCESS_TOKEN_EXPIRE_MINUTES="${ACCESS_TOKEN_EXPIRE_MINUTES:-15}"
REFRESH_TOKEN_EXPIRE_DAYS="${REFRESH_TOKEN_EXPIRE_DAYS:-7}"
BACKEND_PORT="${BACKEND_PORT:-8033}"
FRONTEND_PORT="${FRONTEND_PORT:-3033}"
NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-http://${PUBLIC_IP}:${BACKEND_PORT}}"
ALLOWED_ORIGINS="${ALLOWED_ORIGINS:-[\"http://${PUBLIC_IP}:${FRONTEND_PORT}\",\"http://localhost:${FRONTEND_PORT}\"]}"
LOG_LEVEL="${LOG_LEVEL:-INFO}"
RUN_DB_MIGRATIONS="${RUN_DB_MIGRATIONS:-true}"

if [ ! -f "$ENV_FILE" ]; then
cat > "$ENV_FILE" <<ENVVARS
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
MINIO_SECRET_KEY=$MINIO_SECRET_KEY
MINIO_BUCKET=$MINIO_BUCKET
MINIO_PUBLIC_URL=$MINIO_PUBLIC_URL
MINIO_PORT=$MINIO_PORT
MINIO_CONSOLE_PORT=$MINIO_CONSOLE_PORT
OLLAMA_URL=$OLLAMA_URL
OLLAMA_MODEL=$OLLAMA_MODEL
IA_RESEARCH_PROVIDER=$IA_RESEARCH_PROVIDER
IA_RESEARCH_MODEL=$IA_RESEARCH_MODEL
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY
GEMINI_API_KEY=$GEMINI_API_KEY
SECRET_KEY=$SECRET_KEY
ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
REFRESH_TOKEN_EXPIRE_DAYS=$REFRESH_TOKEN_EXPIRE_DAYS
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
NEXT_PUBLIC_OLLAMA_URL=
ALLOWED_ORIGINS=$ALLOWED_ORIGINS
LOG_LEVEL=$LOG_LEVEL
RUN_DB_MIGRATIONS=$RUN_DB_MIGRATIONS
ENVVARS
fi

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --build

backend_ok=0
for i in $(seq 1 45); do
  if curl -sf "http://localhost:${BACKEND_PORT}/health" >/dev/null 2>&1; then backend_ok=1; break; fi
  sleep 2
done
[ "$backend_ok" = "1" ] || { echo "ERROR: backend no responde"; docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs backend --tail=120 || true; exit 1; }

AUTO_RESTORE_DB="${AUTO_RESTORE_DB:-false}"
DB_DUMP_PATH="${DB_DUMP_PATH:-$ROOT_DIR/db_dump/sgs_prod_dump_latest.sql}"
if [ "$AUTO_RESTORE_DB" = "true" ] && [ -f "$DB_DUMP_PATH" ] && [ ! -f "$RESTORE_FLAG" ]; then
  cat "$DB_DUMP_PATH" | docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" exec -T db psql -U "$POSTGRES_USER" -d "$POSTGRES_DB"
  date > "$RESTORE_FLAG"
fi

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps
